### ISSUE TITLE
ColliderLayer.CL_NONE documentation is misleading

### ISSUE THREAD

**Issue by AlejandroAlvarezMelucciDCL** [decentraland/documentation#418]
Documentation in https://docs.decentraland.org/creator/development-guide/sdk7/colliders/ is misleading, since the client can't have `none` as value due to defaulting to CL_PHYSICS & CL_POINTER.

Technical explanation: `CL_NONE` enum value is `0`, which is bitwise treated the same as not having a `ColliderLayer` defined, which defaults to `CL_PHYSICS & CL_POINTER`

Easy fix: Remove from documentation `CL_NONE` or clearly state that defaults to `CL_PHYSICS & CL_POINTER`
Complex fix: Refactor collision layers to make `CL_NONE` have an available value (like int.max) and refactor the client to contemplate the `CL_NONE` use case.

**Comment by nearnshaw** [comment]
I opened this as an issue in the SDK repo
https://github.com/decentraland/sdk/issues/1135
